### ISSUE TITLE
PROBLEM: Odvzet dostop do baze

### ISSUE THREAD

**Issue by LucijaFekonja** [LaraNahtigal/opb-recepti#14]
Nekako mi je uspelo priti do situacije, da imam permission denied za bazo sem2023_lucijaf, na kateri delava skupaj z Laro Nahtigal. Baza najverjetneje ni izbrisana, saj še lahko Lara vidi podatke, le jaz ne morem dostopati do njih. Ali obstaja možnost, da spet dostopam do podatkov?
Prilagam izvedene postgresql vrstice. Natančneje sem z zadnjimi štirimi ukazi v ustvari_tabele.sql prišla do te težave.

[1678317163634@@baza.fmf.uni-lj.si@5432@sem2023_lucijaf@public.zip](https://github.com/LaraNahtigal/opb-recepti/files/11787299/1678317163634%40%40baza.fmf.uni-lj.si%405432%40sem2023_lucijaf%40public.zip)

**Comment by majbc1999** [comment]
Živijo,

težava je bila verjetno prišla iz sql stavka, s katerim odvzameš pravice za dostop do baze:
```sql
REVOKE CONNECT ON DATABASE sem2023_lucijaf FROM PUBLIC, lucijaf;
```


Težavo bi rešil 
```sql
GRANT CONNECT ON DATABASE sem2023_lucijaf TO lucijaf;
```

vendar ga seveda ne moreš izvesti, če nimaš dostopa do baze.

Najverjetneje ti bo moral Gašper ponovno odobriti dostop, @gasperxy.

**Comment by majbc1999** [comment]
Možna rešitev: če ima dostop do baze in pravico za deljenje pravic Lara, lahko ona poskusi izvesti 

```sql
GRANT CONNECT ON DATABASE sem2023_lucijaf TO lucijaf;
```

**Comment by LucijaFekonja** [comment]
Super! Hvala, je delovalo.
